### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference: when default region that is not us-east-1 is defined in profile

### ISSUE THREAD

**Issue by Sjeanpierre** [Sjeanpierre/osx_vpn_manager#11]
reported by KarlB

**Comment by Sjeanpierre** [comment]
$ sudo vpn host refresh
Refreshing hosts list for profile: XXXX
fetching vpc details for region: us-east-1
fetching vpc details for region: us-west-1
fetching vpc details for region: us-west-2
fetching vpc details for region: eu-west-1
fetching vpc details for region: eu-central-1
fetching vpc details for region: sa-east-1
fetching instances with tag vpn in: us-east-1
fetching instances with tag vpn in: us-west-1
fetching instances with tag vpn in: us-west-2
fetching instances with tag vpn in: eu-west-1
fetching instances with tag vpn in: eu-central-1
fetching instances with tag vpn in: sa-east-1
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8c06]

goroutine 1 [running]:
panic(0x61adc0, 0xc8200140b0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.listVpnInstnaces(0xc820115bc0, 0xc820015e20, 0xd, 0x0, 0x0, 0x0)
	/Users/jstevenson/src/misc/go/src/github.com/sjeanpierre/osx_vpn_manager/vpn_host_manager.go:110 +0x116
main.refreshHosts()
	/Users/jstevenson/src/misc/go/src/github.com/sjeanpierre/osx_vpn_manager/vpn_host_manager.go:140 +0x20e
main.hostFunctions(0xc820015e00, 0xc)
	/Users/jstevenson/src/misc/go/src/github.com/sjeanpierre/osx_vpn_manager/main.go:63 +0xb4
main.main()
	/Users/jstevenson/src/misc/go/src/github.com/sjeanpierre/osx_vpn_manager/main.go:108 +0x8f

**Comment by Sjeanpierre** [comment]
Issues resolved in  	f1b6822
