### ISSUE TITLE
Error running vpn host refresh

### ISSUE THREAD

**Issue by angelamancini** [Sjeanpierre/osx_vpn_manager#9]
I was having trouble connecting to a vpn so I uninstalled and reinstalled and got the following error running `vpn host refresh`

```
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x33cac4]

goroutine 142 [running]:
runtime.throw(0x71c8f0, 0x5)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8200e3880 sp=0xc8200e3868
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc8200e38d0 sp=0xc8200e3880
net/http.(*Transport).dial(0xc8200da000, 0x71eb50, 0x3, 0xc8202e0990, 0x22, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:659 +0x94 fp=0xc8200e3960 sp=0xc8200e38d0
net/http.(*Transport).dialConn(0xc8200da000, 0x0, 0xc820296c90, 0x5, 0xc8202e0990, 0x22, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:762 +0x1e3d fp=0xc8200e3f00 sp=0xc8200e3960
net/http.(*Transport).getConn.func4(0xc8200da000, 0x0, 0xc820296c90, 0x5, 0xc8202e0990, 0x22, 0xc8201e9aa0)
	/usr/local/go/src/net/http/transport.go:706 +0x66 fp=0xc8200e3f78 sp=0xc8200e3f00
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200e3f80 sp=0xc8200e3f78
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:708 +0x262

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc8200da000, 0xc8203ae2a0, 0x0, 0xc820296c90, 0x5, 0xc8202e0990, 0x22, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:711 +0x4ef
net/http.(*Transport).RoundTrip(0xc8200da000, 0xc8203ae2a0, 0xc8200da000, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:311 +0x7e9
net/http.send(0xc8203ae2a0, 0xc71590, 0xc8200da000, 0x0, 0x0, 0x0, 0xc8202e0930, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xad66a0, 0xc8203ae2a0, 0x0, 0x0, 0x0, 0x4e, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xad66a0, 0xc8203ae2a0, 0x869f50, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xad66a0, 0xc8203ae2a0, 0x7a84c0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:191 +0x1e4
github.com/aws/aws-sdk-go/aws/corehandlers.glob.func2(0xc8204f6000)
	/Users/jstevenson/src/misc/go/src/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go:73 +0x55
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc8204f6168, 0xc8204f6000)
	/Users/jstevenson/src/misc/go/src/github.com/aws/aws-sdk-go/aws/request/handlers.go:136 +0xc3
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc8204f6000, 0x0, 0x0)
	/Users/jstevenson/src/misc/go/src/github.com/aws/aws-sdk-go/aws/request/request.go:271 +0x560
github.com/aws/aws-sdk-go/service/ec2.(*EC2).DescribeInstances(0xc8205d61e8, 0xc82037bcc0, 0x3, 0x0, 0x0)
	/Users/jstevenson/src/misc/go/src/github.com/aws/aws-sdk-go/service/ec2/api.go:3403 +0x4f
main.listFilteredInstances(0x71ef20, 0x3, 0xc820142088, 0x6, 0x0, 0x0, 0x0)
	/Users/jstevenson/src/misc/go/src/github.com/sjeanpierre/osx_vpn_manager/vpn_host_manager.go:79 +0x83a
main.listVpnInstnaces(0xc820296ab0, 0xc820142088, 0x6, 0x0, 0x0, 0x0)
	/Users/jstevenson/src/misc/go/src/github.com/sjeanpierre/osx_vpn_manager/vpn_host_manager.go:106 +0x89
main.refreshHosts()
	/Users/jstevenson/src/misc/go/src/github.com/sjeanpierre/osx_vpn_manager/vpn_host_manager.go:140 +0x20e
main.hostFunctions(0xc820011e60, 0xc)
	/Users/jstevenson/src/misc/go/src/github.com/sjeanpierre/osx_vpn_manager/main.go:63 +0xb4
main.main()
	/Users/jstevenson/src/misc/go/src/github.com/sjeanpierre/osx_vpn_manager/main.go:108 +0x8f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 148 [select]:
net/http.(*persistConn).writeLoop(0xc8201176c0)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb

goroutine 147 [IO wait]:
net.runtime_pollWait(0xc72ed0, 0x72, 0xc820467c00)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8202e33a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202e33a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202e3340, 0xc820467c00, 0x400, 0x400, 0x0, 0xc6d050, 0xc8200101a0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820512000, 0xc820467c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8202b6090, 0xc72fe0, 0xc820512000, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc82051e000, 0x86a417, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc82051e000, 0xc82037d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0xc834e0, 0xc82051e000, 0xc820117728, 0xc82037d000, 0x1000, 0x1000, 0x126c3, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc8203d3f20, 0xc82037d000, 0x1000, 0x1000, 0xc8204fdd0d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8202cf020)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8202cf020, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8201176c0)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 150 [select]:
net/http.(*persistConn).writeLoop(0xc820117e10)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb

goroutine 91 [select]:
net/http.(*persistConn).writeLoop(0xc8201a8a90)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb

goroutine 90 [IO wait]:
net.runtime_pollWait(0xc72e10, 0x72, 0xc82057b000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820104df0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820104df0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820104d90, 0xc82057b000, 0x1000, 0x1000, 0x0, 0xc6d050, 0xc8200101a0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a070, 0xc82057b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820210420, 0xc72fe0, 0xc82002a070, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc82059e900, 0x86a417, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc82059e900, 0xc8204ea000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0xc834e0, 0xc82059e900, 0xc8201a8af8, 0xc8204ea000, 0x1000, 0x1000, 0x126c3, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc8203c7960, 0xc8204ea000, 0x1000, 0x1000, 0xc820199d0d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc82048a9c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82048a9c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8201a8a90)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 106 [IO wait]:
net.runtime_pollWait(0xc72bd0, 0x72, 0xc820120c00)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8202e2ae0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202e2ae0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202e2a80, 0xc820120c00, 0x400, 0x400, 0x0, 0xc6d050, 0xc8200101a0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8205d60e0, 0xc820120c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820364c90, 0xc72fe0, 0xc8205d60e0, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc82026c000, 0x86a417, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc82026c000, 0xc8204a9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0xc834e0, 0xc82026c000, 0xc820116e38, 0xc8204a9000, 0x1000, 0x1000, 0x126c3, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc8203e5a80, 0xc8204a9000, 0x1000, 0x1000, 0xc8204f9d0d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820515ce0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820515ce0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820116dd0)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 107 [select]:
net/http.(*persistConn).writeLoop(0xc820116dd0)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb

goroutine 149 [IO wait]:
net.runtime_pollWait(0xc72c90, 0x72, 0xc820099000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8202e2a00, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202e2a00, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202e29a0, 0xc820099000, 0x1000, 0x1000, 0x0, 0xc6d050, 0xc8200101a0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8205d61a8, 0xc820099000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8203336e0, 0xc72fe0, 0xc8205d61a8, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc82026c600, 0x86a417, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc82026c600, 0xc820275000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0xc834e0, 0xc82026c600, 0xc820117e78, 0xc820275000, 0x1000, 0x1000, 0x126c3, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc82039c040, 0xc820275000, 0x1000, 0x1000, 0xc82019bd0d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8202cf260)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8202cf260, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820117e10)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 154 [IO wait]:
net.runtime_pollWait(0xc72d50, 0x72, 0xc820335400)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200a3250, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200a3250, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200a31f0, 0xc820335400, 0x400, 0x400, 0x0, 0xc6d050, 0xc8200101a0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820512a18, 0xc820335400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201eb470, 0xc72fe0, 0xc820512a18, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc82051e900, 0x86a417, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc82051e900, 0xc820542000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0xc834e0, 0xc82051e900, 0xc8200647b8, 0xc820542000, 0x1000, 0x1000, 0x126c3, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc82036a160, 0xc820542000, 0x1000, 0x1000, 0xc820433d0d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8201acfc0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8201acfc0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820064750)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 155 [select]:
net/http.(*persistConn).writeLoop(0xc820064750)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb
```

**Comment by Sjeanpierre** [comment]
Issue resolved in  	f1b6822
